/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NamespaceIndexRouteImport } from './routes/$namespace/index'
import { Route as NamespacesIndexRouteImport } from './routes/namespaces/index'
import { Route as NamespacesPageRouteImport } from './routes/namespaces/$page'
import { Route as NamespaceImageIndexRouteImport } from './routes/$namespace/$image/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespaceIndexRoute = NamespaceIndexRouteImport.update({
  id: '/$namespace/',
  path: '/$namespace/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesIndexRoute = NamespacesIndexRouteImport.update({
  id: '/namespaces/',
  path: '/namespaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesPageRoute = NamespacesPageRouteImport.update({
  id: '/namespaces/$page',
  path: '/namespaces/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespaceImageIndexRoute = NamespaceImageIndexRouteImport.update({
  id: '/$namespace/$image/',
  path: '/$namespace/$image/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/namespaces/$page': typeof NamespacesPageRoute
  '/$namespace/': typeof NamespaceIndexRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/$namespace/$image/': typeof NamespaceImageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/namespaces/$page': typeof NamespacesPageRoute
  '/$namespace': typeof NamespaceIndexRoute
  '/namespaces': typeof NamespacesIndexRoute
  '/$namespace/$image': typeof NamespaceImageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/namespaces/$page': typeof NamespacesPageRoute
  '/$namespace/': typeof NamespaceIndexRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/$namespace/$image/': typeof NamespaceImageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/namespaces/$page'
    | '/$namespace/'
    | '/namespaces/'
    | '/$namespace/$image/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/namespaces/$page'
    | '/$namespace'
    | '/namespaces'
    | '/$namespace/$image'
  id:
    | '__root__'
    | '/'
    | '/namespaces/$page'
    | '/$namespace/'
    | '/namespaces/'
    | '/$namespace/$image/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NamespacesPageRoute: typeof NamespacesPageRoute
  NamespaceIndexRoute: typeof NamespaceIndexRoute
  NamespacesIndexRoute: typeof NamespacesIndexRoute
  NamespaceImageIndexRoute: typeof NamespaceImageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$namespace/': {
      id: '/$namespace/'
      path: '/$namespace'
      fullPath: '/$namespace/'
      preLoaderRoute: typeof NamespaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/': {
      id: '/namespaces/'
      path: '/namespaces'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof NamespacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/$page': {
      id: '/namespaces/$page'
      path: '/namespaces/$page'
      fullPath: '/namespaces/$page'
      preLoaderRoute: typeof NamespacesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$namespace/$image/': {
      id: '/$namespace/$image/'
      path: '/$namespace/$image'
      fullPath: '/$namespace/$image/'
      preLoaderRoute: typeof NamespaceImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NamespacesPageRoute: NamespacesPageRoute,
  NamespaceIndexRoute: NamespaceIndexRoute,
  NamespacesIndexRoute: NamespacesIndexRoute,
  NamespaceImageIndexRoute: NamespaceImageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
